### ISSUE TITLE
[v1.3.3 mc 1.20.4] Server crash on interaction with Stapler and Serger

### ISSUE THREAD

**Issue by MetalDracon** [falkreon/Scarves#11]
I am setting up a server to play with friends, and created my own mod pack for this. While testing the pack on the server the server would crash when ever I tried to interact with either the Scarf Stapler or Serger. At a glance the log is throwing a unexpected exception error for the field backgroundPainter. Attached is a server error log with from the server crashing from this issue.
[latest.log](https://github.com/falkreon/Scarves/files/14941889/latest.log)

**Comment by MetalDracon** [comment]
near dupe of #10 but with different versions of game and mod

**Comment by hatkidchan** [comment]
Not a near dupe, this is the exact bug, only difference being that your log mentions scarf serger and not stapler.

As a workaround for now, just don't use either of those blocks on server and edit NBT directly in any means you find more convenient (`/give`, `/data`, NBTEditor mod, etc), that's what I've been doing

Example: `/give @s scarves:scarf{LeftScarf:[{Id:"minecraft:block/red_wool"},{Id:"minecraft:block/orange_wool"},{Id:"minecraft:block/yellow_wool"},{Id:"minecraft:block/lime_wool"},{Id:"minecraft:block/cyan_wool"},{Id:"minecraft:block/blue_wool"},{Id:"minecraft:block/purple_wool"},{Id:"minecraft:block/magenta_wool"}],RightScarf:[{Id:"minecraft:block/red_wool"},{Id:"minecraft:block/orange_wool"},{Id:"minecraft:block/yellow_wool"},{Id:"minecraft:block/lime_wool"},{Id:"minecraft:block/cyan_wool"},{Id:"minecraft:block/blue_wool"},{Id:"minecraft:block/purple_wool"},{Id:"minecraft:block/magenta_wool"}]}`

**Comment by MetalDracon** [comment]
> Not a near dupe, this is the exact bug, only difference being that your log mentions scarf serger and not stapler.
> 
> As a workaround for now, just don't use either of those blocks on server and edit NBT directly in any means you find more convenient (`/give`, `/data`, NBTEditor mod, etc), that's what I've been doing
> 
> Example: `/give @s scarves:scarf{LeftScarf:[{Id:"minecraft:block/red_wool"},{Id:"minecraft:block/orange_wool"},{Id:"minecraft:block/yellow_wool"},{Id:"minecraft:block/lime_wool"},{Id:"minecraft:block/cyan_wool"},{Id:"minecraft:block/blue_wool"},{Id:"minecraft:block/purple_wool"},{Id:"minecraft:block/magenta_wool"}],RightScarf:[{Id:"minecraft:block/red_wool"},{Id:"minecraft:block/orange_wool"},{Id:"minecraft:block/yellow_wool"},{Id:"minecraft:block/lime_wool"},{Id:"minecraft:block/cyan_wool"},{Id:"minecraft:block/blue_wool"},{Id:"minecraft:block/purple_wool"},{Id:"minecraft:block/magenta_wool"}]}`

Thanks for confirming that it is the same bug, I honestly can't read logs well enough to have been sure myself. 

Additionally, thanks for the command example while I editing the nbt had crossed my mind, it probably would have taken me around an hour or two to figure out the command.

Do you think I should close this thread as not planned because it is a duplicate issue for the same bug?

**Comment by hatkidchan** [comment]
Probably, since we already cross-referenced issues on both of them and problem appears to be exactly the same. I'll update name of mine to reflect your problem too

**Comment by MetalDracon** [comment]
Ok, sounds good I will close my thread so that there aren't duplicate threads.
