### ISSUE TITLE
Are you actually able to put arbitrary items in the scarf stapler? Becuse I can't

### ISSUE THREAD

**Issue by Sea-Kerman** [falkreon/Scarves#4]
What items are you allowed to add to scarves?

**Comment by falkreon** [comment]
Without any other mods attached, the following items are valid:
- Any color Wool Block
- Lava bucket (the bucket is consumed)
- Water bucket (the bucket is consumed)
- Glowstone Block
- Another scarf, provided that it only has one tail (the scarf is consumed)
- Any item that has a "FabricSquare" NBT compound key via data command or other means
