### ISSUE TITLE
show scarf colours in the inventory

### ISSUE THREAD

**Issue by Abbie5** [falkreon/Scarves#8]
currently, scarves all look the same when in the inventory. it would be nice if the item model reflected the scarf colours. i have provided a mock-up of what this might look like.

currently:
![image](https://github.com/falkreon/Scarves/assets/43531981/b291f3c1-b9cc-4646-bdd6-418e99a9bae5)

mock-up:
![scarves mockup](https://github.com/falkreon/Scarves/assets/43531981/6d4a7ed5-ec27-47a9-927b-42da3f416f9d)

**Comment by falkreon** [comment]
I've been thinking about slicing the scarf up into 4-ish pieces, each with a different colorIndex, so they could show at least the first four colors in the scarf which would help a lot. Didn't have time before BlanketCon but this is definitely a possibility after!

**Comment by falkreon** [comment]
Fixed as of [37de87e](https://github.com/falkreon/Scarves/commit/37de87e12f27d40a19ca37d090f702ddbc7396d2) (!!!)
